owncloud:
    image: owncloud
    ports:
     - 8080:80
    volumes_from:
      - owncloud-data
    links:
     - mariadb:db
    hostname: cloud
    domainname: owncloud.local
    restart: always
    environment:
      - VIRTUAL_HOST=owncloud.local

mariadb:
    image: mariadb
    hostname: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes_from:
      - mariadb-data
    restart: always

mariadb-data:
    image: busybox
    hostname: mariadb-data
    command: /bin/sh -c "/bin/chown -R 999 /var/lib/mysql"
    volumes:
      - /var/lib/mysql

owncloud-data:
    image: busybox
    hostname: owncloud-data
    command: /bin/sh -c "/bin/chown -R 33 /var/www/html/data && /bin/chown -R 33 /var/www/html/config"
    volumes:
      - /var/www/html/data
      - /var/www/html/config

nginx-certs:
    image: alpine
    hostname: nginx-certs
    command: apk-install openssl ; /usr/bin/openssl genrsa -out /etc/nginx/certs/owncloud.local.key 1024 && \
    /usr/bin/openssl req  -new -newkey rsa:4096 -days 365 -nodes -subj "/C=/ST=/L=/O=/CN=OwnCloud" -keyout /etc/nginx/certs/owncloud.local.key -out /etc/nginx/certs/owncloud.csr  && \
    /usr/bin/openssl x509 -req -days 365 -in /etc/nginx/certs/owncloud.local.csr -signkey /etc/nginx/certs/owcloud.local.key -out /etc/nginx/certs/owncloud.local.crt

    volumes:
      - /etc/nginx/certs

nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - nginx-certs
